#import "Basic";

main :: () {
  print("Hello world!\n");
  print("Bonjour tout le monde!\n");
  print("Hallo Wereld!\n");
  print("¡Hola, mundo!\n"); // (4)
  print("Καλημέρα κόσμε!\n");
  print("こんにちは 世界!\n"); 
  print("!ہیلو ، دنیا\n");
  print("ສະ​ບາຍ​ດີ​ຊາວ​ໂລກ\n");
  print("👋🌍❗\n");

  print("\u03C0");  // => π
}

/*
Hello world!
Bonjour tout le monde!
Hallo Wereld!
¡Hola, mundo!
Καλημέρα κόσμε!
こんにちは 世界!
!ہیلو ، دنیا
ສະ​ບາຍ​ດີ​ຊາວ​ໂລກ
👋🌍❗
π
*/